// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated on every `next build` (prebuild hook). Tracked in git so
// typecheck/lint/test have a valid module without a build; a local build may
// leave this file dirty with the local SHA — harmless (CI/Vercel regenerate).
export const APP_VERSION = {
  "version": "1.0.0",
  "commit": "58f9739570a89211a5c905f85429cd3dbdf74ae5",
  "shortCommit": "58f9739",
  "branch": "feat/mobile-opt-main",
  "buildTime": "2026-06-27T15:54:24.150Z"
} as const;

export type AppVersion = typeof APP_VERSION;
