#!/usr/bin/env node
/**
 * generate-version.mjs — single source of truth for the app's build identity.
 *
 * Runs as the `prebuild` npm hook (fires automatically before `next build`, on
 * Vercel AND locally). Computes one { version, commit, shortCommit, branch,
 * buildTime } object and writes it to BOTH:
 *   - public/version.json   → served at /version.json = "what's deployed"
 *   - src/lib/version.ts     → APP_VERSION constant, imported into the bundle =
 *                              "what's running" (baked into the JS at build time)
 *
 * Because both come from ONE run, they are equal for any given build; across
 * builds they differ — and that difference is exactly the "update available"
 * signal the client compares (see src/lib/version-check.ts).
 *
 * Commit SHA source: Vercel's build env var first (canonical on prod), then a
 * local `git` fallback (dev), then 'unknown' (the client treats 'unknown' as
 * "no info" and never shows the update banner — no false positives).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';

const sh = (cmd) => {
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
};

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));

const commit = process.env.VERCEL_GIT_COMMIT_SHA || sh('git rev-parse HEAD') || 'unknown';
const branch =
  process.env.VERCEL_GIT_COMMIT_REF || sh('git rev-parse --abbrev-ref HEAD') || 'unknown';

const info = {
  version: pkg.version,
  commit,
  shortCommit: commit === 'unknown' ? 'unknown' : commit.slice(0, 7),
  branch,
  buildTime: new Date().toISOString(),
};

// public/version.json (served static) — ensure public/ exists first.
if (!existsSync('public')) mkdirSync('public', { recursive: true });
writeFileSync('public/version.json', JSON.stringify(info, null, 2) + '\n');

// src/lib/version.ts (baked into bundle). AUTO-GENERATED — do not hand-edit.
const ts =
  `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.\n` +
  `// Regenerated on every \`next build\` (prebuild hook). Tracked in git so\n` +
  `// typecheck/lint/test have a valid module without a build; a local build may\n` +
  `// leave this file dirty with the local SHA — harmless (CI/Vercel regenerate).\n` +
  `export const APP_VERSION = ${JSON.stringify(info, null, 2)} as const;\n` +
  `\nexport type AppVersion = typeof APP_VERSION;\n`;
writeFileSync('src/lib/version.ts', ts);

console.log('[version]', info.version, '·', info.shortCommit, '(' + info.branch + ')');
